---
- name: global
  description: 'Global'
- name: curve_1
  description: 'Curve #1: Based on economic security'
- name: curve_2
  description: 'Curve #2: Based on network size'
- name: ui
  description: 'UI'
---
floats:
  - name: E
    value: 6.8
    min: 0.0
    max: 20.0
    step: 0.1
    description: 'V. Offset'
    group: global
  
  - name: B1
    value: 7.5
    min: 0.0
    max: 10.0
    step: 0.01
    description: 'Flatness'
    group: curve_1
  
  - name: K1
    value: 0.5
    min: 0.0
    max: 1.0
    step: 0.01
    description: 'Maximum ratio'
    group: curve_1
  
  - name: nu1
    value: 1.5
    min: 0.0
    max: 5.0
    step: 0.01
    description: 'Skewness'
    group: curve_1
  
  - name: staked_tokens
    value: 0.25
    min: 0.0
    max: 50.0
    step: 0.05
    description: 'Staked tokens'
    group: curve_1
  
  - name: B2
    value: 5.0
    min: 0.0
    max: 10.0
    step: 0.01
    description: 'Flatness'
    group: curve_2
  
  - name: K2
    value: 1.0
    min: 0.0
    max: 1.0
    step: 0.01
    description: 'Maximum ratio'
    group: curve_2
  
  - name: nu2
    value: 2.75
    min: 0.0
    max: 5.0
    step: 0.01
    description: 'Skewness'
    group: curve_2

ints:
  - name: max_token_supply
    value: 70
    min: 50
    max: 100
    step: 2
    description: 'Max. token supply'
    group: curve_1

  - name: node_count
    value: 500
    min: 500
    max: 5000
    step: 10
    description: 'Node count'
    group: curve_2
  
  - name: max_node_count
    value: 2000
    min: 500
    max: 5000
    step: 10
    description: 'Max. node count'
    group: curve_2
  
  - name: alpha
    value: 20
    min: 0
    max: 90
    step: 5
    description: 'Alpha'
    group: ui
  
  - name: theta
    value: 30
    min: 0
    max: 90
    step: 5
    description: 'Theta'
    group: ui
...